import {
  UserProfile,
  Destination,
  Trip,
  PackingItem,
  ItineraryDay,
  BudgetSummary,
  EmergencyContact,
  SafetyPrinciple,
  TravelerMatch,
  CostSharePost,
} from '../types';

export const mockUser: UserProfile = {
  id: 'user_alex_1',
  name: 'Alex Rivera',
  email: 'alex@example.com',
  avatarInitials: 'AR',
  location: 'Madrid, Spain',
  persona: 'Adventure',
  countriesVisited: 12,
  totalDays: 47,
  totalTrips: 8,
  bio: 'Photographer & slow explorer. Exploring ancient alleys, mountain trails, and local espresso bars.',
  languages: ['English', 'Spanish', 'Japanese (Basic)'],
  isVerified: true,
};

export const mockUpcomingTrip: Trip = {
  id: 'trip_kyoto_2026',
  destination: 'Kyoto',
  country: 'Japan',
  startDate: 'Sept 22, 2026',
  endDate: 'Oct 1, 2026',
  daysRemaining: 12,
  totalDays: 10,
  imageUrl: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?q=80&w=1200&auto=format&fit=crop',
  status: 'upcoming',
  safetyAttentionCount: 2,
};

export const mockRecentTrips: Trip[] = [
  {
    id: 'trip_thailand_1',
    destination: 'Bangkok → Chiang Mai',
    country: 'Thailand',
    startDate: 'Mar 2026',
    endDate: 'Mar 2026',
    daysRemaining: 0,
    totalDays: 9,
    imageUrl: 'https://images.unsplash.com/photo-1508009603885-50cf7c579365?q=80&w=800&auto=format&fit=crop',
    status: 'completed',
  },
  {
    id: 'trip_portugal_1',
    destination: 'Lisbon → Porto',
    country: 'Portugal',
    startDate: 'Nov 2025',
    endDate: 'Nov 2025',
    daysRemaining: 0,
    totalDays: 7,
    imageUrl: 'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?q=80&w=800&auto=format&fit=crop',
    status: 'completed',
  },
  {
    id: 'trip_japan_past',
    destination: 'Tokyo → Kyoto → Osaka',
    country: 'Japan',
    startDate: 'Aug 2025',
    endDate: 'Aug 2025',
    daysRemaining: 0,
    totalDays: 14,
    imageUrl: 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?q=80&w=800&auto=format&fit=crop',
    status: 'completed',
  },
];

export const mockTrendingDestinations: Destination[] = [
  {
    id: 'dest_kyoto',
    name: 'Kyoto',
    country: 'Japan',
    tagline: 'Temples, moss gardens & matcha tranquility',
    category: 'Culture',
    dailyCost: 55,
    safetyScore: 98,
    imageUrl: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?q=80&w=800&auto=format&fit=crop',
    region: 'Asia',
    description: 'Kyoto offers an incomparable blend of preserved wooden architecture, serene bamboo groves, and rich heritage cuisine perfect for solo wanderers.',
    bestTimeToVisit: 'March–May & October–November',
    popularActivities: ['Fushimi Inari Sunrise Hike', 'Arashiyama Bamboo Grove', 'Gion Evening Stroll'],
  },
  {
    id: 'dest_medellin',
    name: 'Medellín',
    country: 'Colombia',
    tagline: 'Cable cars & hostel culture',
    category: 'City',
    dailyCost: 38,
    safetyScore: 91,
    imageUrl: 'https://images.unsplash.com/photo-1599839575945-a9e5af0c3fa5?q=80&w=800&auto=format&fit=crop',
    region: 'Americas',
    description: 'The City of Eternal Spring boasts world-class public transit, blooming coffee culture, and an energetic, welcoming nomad community.',
    bestTimeToVisit: 'December–March',
    popularActivities: ['Comuna 13 Graffiti Tour', 'Guatapé Day Trip', 'Poblado Coffee Crawl'],
  },
  {
    id: 'dest_reykjavik',
    name: 'Reykjavík',
    country: 'Iceland',
    tagline: 'Auroras & midnight sun hikes',
    category: 'Nature',
    dailyCost: 120,
    safetyScore: 96,
    imageUrl: 'https://images.unsplash.com/photo-1504893524553-b855bce32c67?q=80&w=800&auto=format&fit=crop',
    region: 'Europe',
    description: 'Vibrant Nordic capital with unmatched geothermal lagoons, majestic waterfalls, and safe, well-marked solo trekking routes.',
    bestTimeToVisit: 'September–April (Auroras) or June–August',
    popularActivities: ['Golden Circle Solo Drive', 'Sky Lagoon Bath', 'Volcano Hike'],
  },
  {
    id: 'dest_hoian',
    name: 'Hội An',
    country: 'Vietnam',
    tagline: 'Lanterns & $2 pho at dawn',
    category: 'Food',
    dailyCost: 28,
    safetyScore: 94,
    imageUrl: 'https://images.unsplash.com/photo-1528127269322-539801943592?q=80&w=800&auto=format&fit=crop',
    region: 'Asia',
    description: 'A glowing ancient trading port with mouthwatering street food, custom tailor shops, and tranquil riverfront night walks.',
    bestTimeToVisit: 'February–July',
    popularActivities: ['Early Morning Banh Mi Quest', 'An Bang Beach Cycling', 'Lantern Night Boat Ride'],
  },
  {
    id: 'dest_porto',
    name: 'Porto',
    country: 'Portugal',
    tagline: 'Azulejo tiles & sunset views',
    category: 'Wine & Art',
    dailyCost: 62,
    safetyScore: 95,
    imageUrl: 'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?q=80&w=800&auto=format&fit=crop',
    region: 'Europe',
    description: 'Charming Douro river vistas, historic wine cellars, tile-adorned churches, and warm Portuguese hospitality.',
    bestTimeToVisit: 'May–September',
    popularActivities: ['Dom Luís I Bridge Sunset', 'Livraria Lello Visit', 'Douro Valley Train Ride'],
  },
  {
    id: 'dest_tbilisi',
    name: 'Tbilisi',
    country: 'Georgia',
    tagline: 'Fortress city, wine & warmth',
    category: 'City',
    dailyCost: 32,
    safetyScore: 92,
    imageUrl: 'https://images.unsplash.com/photo-1565008447742-97f6f38c985c?q=80&w=800&auto=format&fit=crop',
    region: 'Hidden Gems',
    description: 'Ancient sulfur baths, cliffside fortresses, endless natural wine bars, and remarkably welcoming locals.',
    bestTimeToVisit: 'May–June & September–October',
    popularActivities: ['Narikala Fortress Cable Car', 'Sulfur Bath Experience', 'Fabrika Social Hub'],
  },
];

export const mockPackingItems: PackingItem[] = [
  { id: 'p_1', title: 'Passport + photocopies', category: 'DOCUMENTS', isPacked: true },
  { id: 'p_2', title: 'Travel insurance docs', category: 'DOCUMENTS', isPacked: false },
  { id: 'p_3', title: 'Unlocked SIM-ready phone', category: 'TECH', isPacked: true },
  { id: 'p_4', title: 'Universal power adapter', category: 'TECH', isPacked: true },
  { id: 'p_5', title: '35L carry-on backpack', category: 'GEAR', isPacked: false },
  { id: 'p_6', title: 'Packing cubes', category: 'GEAR', isPacked: false },
  { id: 'p_7', title: 'Microfibre towel', category: 'GEAR', isPacked: false },
  { id: 'p_8', title: 'First aid kit', category: 'HEALTH', isPacked: false },
  { id: 'p_9', title: 'Multi-currency travel debit card', category: 'FINANCE', isPacked: false },
  { id: 'p_10', title: 'Emergency cash ($100 USD & Yen)', category: 'FINANCE', isPacked: false },
];

export const mockItineraryDays: ItineraryDay[] = [
  {
    id: 'it_1',
    dayNumber: 1,
    tag: 'Free',
    title: 'Arrive & Orient',
    description: 'Book one walking tour. Nothing else.',
    activities: ['Check-in at hostel/ryokan', 'Gion evening orientation stroll', 'Ramen dinner at Ichiran'],
  },
  {
    id: 'it_2',
    dayNumber: 2,
    tag: 'Full day',
    title: 'Neighbourhood Dive',
    description: 'Pick one district. Eat where locals queue.',
    activities: ['Higashiyama historical streets', 'Kiyomizu-dera early morning visit', 'Nishiki Market food tour'],
  },
  {
    id: 'it_3',
    dayNumber: 3,
    tag: 'Early start',
    title: 'Day Trip by Train',
    description: 'Always better than taxis.',
    activities: ['JR Train to Arashiyama', 'Tenryu-ji Temple Zen garden', 'Scenic Sagano Romantic Train'],
  },
  {
    id: 'it_4',
    dayNumber: 4,
    tag: 'Flexible',
    title: 'Slow Morning',
    description: 'Market, café, notebook. No agenda.',
    activities: ['Single-origin matcha café session', 'Philosopher’s Path walk', 'Journaling & photo editing'],
  },
  {
    id: 'it_5',
    dayNumber: 5,
    tag: 'Full day',
    title: 'Hidden Gem Day',
    description: 'Ask your guesthouse, not Google.',
    activities: ['Kurama to Kibune mountain hike', 'Traditional open-air Onsen bath', 'Riverside dinner on kawadoko platform'],
  },
];

export const mockBudgetSummary: BudgetSummary = {
  totalBudget: 1200,
  totalSpent: 437,
  currency: '$',
  categories: [
    { category: 'Flights', amount: 210, color: '#00E5FF', percentage: 48 },
    { category: 'Accommodation', amount: 124, color: '#00D2B4', percentage: 28 },
    { category: 'Food & Drink', amount: 68, color: '#8B5CF6', percentage: 16 },
    { category: 'Transport', amount: 35, color: '#FF3B69', percentage: 8 },
  ],
};

export const mockEmergencyContact: EmergencyContact = {
  id: 'ec_1',
  name: 'María Rivera',
  phone: '+34 612 345 678',
  relationship: 'Mother',
  avatarInitials: 'MR',
};

export const mockSafetyPrinciples: SafetyPrinciple[] = [
  {
    id: 'sp_1',
    icon: 'shield',
    title: 'Share your itinerary',
    description: 'Send plans to someone at home before each leg.',
  },
  {
    id: 'sp_2',
    icon: 'wifi',
    title: 'Get a local SIM immediately',
    description: 'Data independence = safety independence.',
  },
  {
    id: 'sp_3',
    icon: 'phone',
    title: 'Save emergency numbers',
    description: 'Store police, medical, and embassy offline.',
  },
  {
    id: 'sp_4',
    icon: 'map-pin',
    title: 'Pin your accommodation offline',
    description: 'Always download the offline map area before leaving Wi-Fi.',
  },
];

export const mockTravelerMatches: TravelerMatch[] = [
  {
    id: 'tm_1',
    name: 'Elena Rostova',
    ageRange: '26',
    country: 'Spain',
    avatarInitials: 'ER',
    destination: 'Kyoto, Japan',
    travelDates: 'Sept 23 — Oct 2, 2026',
    travelStyle: 'Adventure',
    interests: ['Photography', 'Hiking', 'Street Food'],
    approxBudget: '$50–70/day',
    compatibilityScore: 96,
    isVerified: true,
    bio: 'Looking for a companion to do the early sunrise Fushimi Inari hike and share sushi dinners.',
  },
  {
    id: 'tm_2',
    name: 'Lucas Meyer',
    ageRange: '29',
    country: 'Germany',
    avatarInitials: 'LM',
    destination: 'Kyoto, Japan',
    travelDates: 'Sept 20 — Sept 30, 2026',
    travelStyle: 'Culture',
    interests: ['Architecture', 'History', 'Coffee'],
    approxBudget: '$60/day',
    compatibilityScore: 91,
    isVerified: true,
    bio: 'Architect visiting ancient wooden shrines and temple gardens. Down for coffee and gallery visits.',
  },
  {
    id: 'tm_3',
    name: 'Chloe Chen',
    ageRange: '24',
    country: 'Canada',
    avatarInitials: 'CC',
    destination: 'Kyoto & Osaka',
    travelDates: 'Sept 24 — Oct 5, 2026',
    travelStyle: 'Slow Travel',
    interests: ['Tea Ceremonies', 'Cycling', 'Art'],
    approxBudget: '$45/day',
    compatibilityScore: 88,
    isVerified: true,
    bio: 'Slow traveler renting a bike for the week in Kyoto. Love quiet temples and vintage bookshops.',
  },
];

export const mockCostSharePosts: CostSharePost[] = [
  {
    id: 'cs_1',
    title: 'Traditional Machiya Ryokan Room Share',
    destination: 'Gion, Kyoto',
    dates: 'Sept 24 – Sept 27 (3 nights)',
    hostName: 'Elena Rostova',
    hostAvatar: 'ER',
    description: 'Booked a private 2-person traditional tatami room with garden view. Split 50/50 to save on accommodation!',
    totalExpense: 240,
    costPerPerson: 120,
    spotsTotal: 2,
    spotsTaken: 1,
    tags: ['Hostel / Ryokan', 'Female only or mixed', 'Verified members'],
  },
  {
    id: 'cs_2',
    title: 'Mount Fuji & Lake Kawaguchiko Car Rental',
    destination: 'Tokyo → Mount Fuji',
    dates: 'Sept 29 (Full Day)',
    hostName: 'Kenji Sato',
    hostAvatar: 'KS',
    description: 'Renting an SUV to catch sunrise over Chureito Pagoda and explore the 5 lakes. 3 open seats for gas/toll split.',
    totalExpense: 140,
    costPerPerson: 35,
    spotsTotal: 4,
    spotsTaken: 2,
    tags: ['Road Trip', 'Scenic Hike', 'Gas Split'],
  },
];
